spring:
  datasource:
    url: jdbc:mysql://localhost:3306/votesystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 710048
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
server:
  port: 8080
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.vote.pojo